services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r jyyxt.cloud:21117 -k _
    volumes:
      - ./data:/root
    network_mode: "host"
    restart: always

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr -k _
    volumes:
      - ./data:/root
    network_mode: "host"
    restart: always

  version-check:
    container_name: version-check
    image: node:20
    working_dir: /app
    user: "0:0"
    environment:
      ADMIN_PASSWORD: "jiaying"
      SERVER_HOST: "jyyxt.cloud"
      PORT: "3001"
    volumes:
      - ./version-check:/app
      - ./version-check/apk:/app/apk
      - /app/node_modules
    command: sh -c "umask 022 && npm install && node index.js"
    network_mode: "host"
    restart: always